spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 3600000

app:
  auth:
    jwks-url: ${JWKS_URL:https://dev-40otcbcw42xphj6b.us.auth0.com/.well-known/jwks.json}